spring:  application:    name: tax-service      datasource:    url: jdbc:h2:mem:taxdb    driver-class-name: org.h2.Driver    username: ibm    password: ibm     h2:    console:      enabled: true    server:  port: 8090

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    
  client:
    service-url:
      defaultZone:  http://localhost:8100/eureka